[package]
name = "mysh"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
ctor = "0.1.21"
lazy_static = "1.4.0"
which = "4.2"

[target.'cfg(unix)'.dependencies]
users = "0.11.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_Memory",
    "Win32_Storage_FileSystem",
] }
windows-sys = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_Memory"
] }